config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :materials do
    resources :transactions, except: :destroy
  end
  get "/cart", to: "transactions#cart"
  patch "/sale", to: "transactions#sale"
  resources :transactions, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :transactions
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :material
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :transactions
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :find, only: [:show, :edit, :update, :destroy]

  def index
    @materials = Material.all
  end

  def show; end

  def new
    @material = Material.new
  end

  def create
    @material = Material.new(material_params)
    if @material.save!
      redirect_to material_path(@material)
    else
      render :new
    end
  end

  def edit; end

  def update
    @material.update(material_params)
    redirect_to material_path(@material)
  end

  def destroy
    @material.destroy
    redirect_to materials_path
  end

  private

  def find
    @material = Material.find(params[:id])
  end

  def material_params
    params.require(:material).permit(:name, :category, :qty)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :find, only: [:show, :edit, :update, :destroy]
  before_action :set_material, only: [:create, :sale]
  before_action :set_user, only: [:cart]
  before_action :find_in_cart, only: [:create]
  before_action :cart, only: [:update]

  def index
    @transactions = Transaction.all
  end

  def show; end

  def new
    @transaction = Transaction.new
  end

  def create
    unless @transaction # Avoid new material already in cart.
      @transaction = Transaction.new
      @transaction.material = @material
      @transaction.user = current_user
      @transaction.completed = false
      @transaction.delivered = false
      @transaction.amount = 1
      if @transaction.save!
        redirect_to materials_path, notice: " #{@transaction.material.name} adicionado ao carrinho! "
      else
        render :new
      end
    else
      redirect_to cart_path
    end
  end

  def cart
    # Verificar "Janela de Transferência"
    @transactions = Transaction.where(user_id: current_user, delivered: false)
  end

  def edit; end
  
  def update # Confirmação do Pedido
    @transactions.each do |t|
      t.update(transaction_params)
    end
    redirect_to transaction_path(@transaction)
  end

  def sale
    # Verificar em "Janela de Transferência" como acontece a definição da variável @transactions
    # Talvez aqui seja o momento de atualizar as quantidades dos materiais.
    @transactions.each do |t|
      t.update(delivered: true)
    end
    redirect_to root_path, notice: "Itens entregues com sucesso"
  end

  def destroy
    @transaction.destroy
    redirect_to cart_path
  end

  private

  def find
    @transaction = Transaction.find(params[:id])
  end

  def find_in_cart # Verifica se há alguma instância de Transaction com material já presente no carrinho.
    @transaction = Transaction.exists?(material_id: @material.id)
  end

  def set_material
    @material = Material.find(params[:material_id])
  end

  def transaction_params
    params.require(:transaction).permit(:delivered, :completed, :amount, :material_id, :user_id)
  end

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Almoxarifácil</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/materials/edit.html.erb
<%= render "shared/form" %>

app/views/materials/index.html.erb
<h2>Materiais</h2>
<div id="table">
  <table>
    <thead>
      <tr>
        <th> Material</th>
        <th>Quantidade</th>
      </tr>
    </thead>
    <tbody id="body">
      <% @materials.each do |material| %>
        <tr>
          <td><%= link_to material.name, material_path(material.id) %></td>
          <td><%= material.qty %></td>
          <td><%= link_to 'Adicionar ao carrinho', material_transactions_path(material), method: 'post' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/materials/new.html.erb
<%= render "shared/form" %>

app/views/materials/show.html.erb
<h2><%= @material.name %></h2>
<p>Quantidade: <%= @material.qty %></p>
<p><%= link_to 'Editar', edit_material_path(@material) %></p>
<p><%= link_to 'Adicionar ao carrinho', material_transactions_path(@material), method: "post" %></p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= link_to 'Index', materials_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= simple_form_for(@material) do |f| %>
  <%= f.input :name, label: "Material" %>
  <%= f.input :category, label: "Tipo de material" %>
  <%= f.input :qty, label: "Quantidade inicial" %>
  <%= f.submit "Criar material" %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <% if current_user.admin? %>
            <li class="nav-item">
            <%= link_to 'Criar Material', new_material_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Carrinho', cart_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/transactions/cart.html.erb
<h2>Carrinho de <%= @user.email %></h2>


<div>
  <% @transactions.each do |t| %>
    <ul>
      <li><%= t.material.name %> | <%= form_with do |form| %> <%= form.number_field :amount %> <%= form.submit "Atualizar qtd" %> <% end %> | <%= link_to 'Excluir', transaction_path(t), method: :delete, data: { confirm: "Excluir #{t.material.name} do carrinho?" } %></li>
    </ul>
  <% end %>
</div>
<div>
  <%= link_to 'Continuar comprando', materials_path %>
</div>

app/views/transactions/edit.html.erb
<h3>Verificar "Janela de Transferência"</h3>
<p>Pesquisar como utilizar dado inserido no formulário como variável em operação, para só então ser salvo na instância necessária</p>

app/views/transactions/index.html.erb
<div>
    <ul>
      <% @transactions.each do |transaction| %>
        <li><%= transaction.id %> - Usuário: <%= transaction.user.name %></li>
        <% end %>
    </ul>
</div>

app/views/transactions/new.html.erb
<h2>Verificar "Janela de Transferência"</h2>
<p>Incluir campo para mostrar a quantidade requerida</p>

app/views/transactions/show.html.erb
<div>
  <h3><%= @transaction.id %> | <%= @transaction.user.name %></h3>
</div>